// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: lib/config/ldaptransport.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LDAPTransport int32

const (
	LDAPTransport_LDAP_TRANSPORT_PLAIN     LDAPTransport = 0
	LDAPTransport_LDAP_TRANSPORT_TLS       LDAPTransport = 2
	LDAPTransport_LDAP_TRANSPORT_START_TLS LDAPTransport = 3
)

// Enum value maps for LDAPTransport.
var (
	LDAPTransport_name = map[int32]string{
		0: "LDAP_TRANSPORT_PLAIN",
		2: "LDAP_TRANSPORT_TLS",
		3: "LDAP_TRANSPORT_START_TLS",
	}
	LDAPTransport_value = map[string]int32{
		"LDAP_TRANSPORT_PLAIN":     0,
		"LDAP_TRANSPORT_TLS":       2,
		"LDAP_TRANSPORT_START_TLS": 3,
	}
)

func (x LDAPTransport) Enum() *LDAPTransport {
	p := new(LDAPTransport)
	*p = x
	return p
}

func (x LDAPTransport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LDAPTransport) Descriptor() protoreflect.EnumDescriptor {
	return file_lib_config_ldaptransport_proto_enumTypes[0].Descriptor()
}

func (LDAPTransport) Type() protoreflect.EnumType {
	return &file_lib_config_ldaptransport_proto_enumTypes[0]
}

func (x LDAPTransport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LDAPTransport.Descriptor instead.
func (LDAPTransport) EnumDescriptor() ([]byte, []int) {
	return file_lib_config_ldaptransport_proto_rawDescGZIP(), []int{0}
}

var File_lib_config_ldaptransport_proto protoreflect.FileDescriptor

var file_lib_config_ldaptransport_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6c, 0x69, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x6c, 0x64, 0x61,
	0x70, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2a, 0x5f, 0x0a, 0x0d, 0x4c, 0x44, 0x41, 0x50,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x14, 0x4c, 0x44, 0x41,
	0x50, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x49,
	0x4e, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x4c, 0x44, 0x41, 0x50, 0x5f, 0x54, 0x52, 0x41, 0x4e,
	0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x54, 0x4c, 0x53, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x4c,
	0x44, 0x41, 0x50, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x53, 0x54,
	0x41, 0x52, 0x54, 0x5f, 0x54, 0x4c, 0x53, 0x10, 0x03, 0x42, 0x12, 0x5a, 0x10, 0x73, 0x79, 0x6e,
	0x63, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lib_config_ldaptransport_proto_rawDescOnce sync.Once
	file_lib_config_ldaptransport_proto_rawDescData = file_lib_config_ldaptransport_proto_rawDesc
)

func file_lib_config_ldaptransport_proto_rawDescGZIP() []byte {
	file_lib_config_ldaptransport_proto_rawDescOnce.Do(func() {
		file_lib_config_ldaptransport_proto_rawDescData = protoimpl.X.CompressGZIP(file_lib_config_ldaptransport_proto_rawDescData)
	})
	return file_lib_config_ldaptransport_proto_rawDescData
}

var file_lib_config_ldaptransport_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lib_config_ldaptransport_proto_goTypes = []interface{}{
	(LDAPTransport)(0), // 0: config.LDAPTransport
}
var file_lib_config_ldaptransport_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lib_config_ldaptransport_proto_init() }
func file_lib_config_ldaptransport_proto_init() {
	if File_lib_config_ldaptransport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lib_config_ldaptransport_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lib_config_ldaptransport_proto_goTypes,
		DependencyIndexes: file_lib_config_ldaptransport_proto_depIdxs,
		EnumInfos:         file_lib_config_ldaptransport_proto_enumTypes,
	}.Build()
	File_lib_config_ldaptransport_proto = out.File
	file_lib_config_ldaptransport_proto_rawDesc = nil
	file_lib_config_ldaptransport_proto_goTypes = nil
	file_lib_config_ldaptransport_proto_depIdxs = nil
}
