// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: config/tuning.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tuning int32

const (
	Tuning_TUNING_AUTO  Tuning = 0
	Tuning_TUNING_SMALL Tuning = 1
	Tuning_TUNING_LARGE Tuning = 2
)

// Enum value maps for Tuning.
var (
	Tuning_name = map[int32]string{
		0: "TUNING_AUTO",
		1: "TUNING_SMALL",
		2: "TUNING_LARGE",
	}
	Tuning_value = map[string]int32{
		"TUNING_AUTO":  0,
		"TUNING_SMALL": 1,
		"TUNING_LARGE": 2,
	}
)

func (x Tuning) Enum() *Tuning {
	p := new(Tuning)
	*p = x
	return p
}

func (x Tuning) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tuning) Descriptor() protoreflect.EnumDescriptor {
	return file_config_tuning_proto_enumTypes[0].Descriptor()
}

func (Tuning) Type() protoreflect.EnumType {
	return &file_config_tuning_proto_enumTypes[0]
}

func (x Tuning) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tuning.Descriptor instead.
func (Tuning) EnumDescriptor() ([]byte, []int) {
	return file_config_tuning_proto_rawDescGZIP(), []int{0}
}

var File_config_tuning_proto protoreflect.FileDescriptor

var file_config_tuning_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x74, 0x75, 0x6e, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2a, 0x3d, 0x0a,
	0x06, 0x54, 0x75, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x55, 0x4e, 0x49, 0x4e,
	0x47, 0x5f, 0x41, 0x55, 0x54, 0x4f, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x55, 0x4e, 0x49,
	0x4e, 0x47, 0x5f, 0x53, 0x4d, 0x41, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x55,
	0x4e, 0x49, 0x4e, 0x47, 0x5f, 0x4c, 0x41, 0x52, 0x47, 0x45, 0x10, 0x02, 0x42, 0x37, 0x5a, 0x35,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x65, 0x62, 0x66, 0x72,
	0x6f, 0x73, 0x73, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2d, 0x6d, 0x6f,
	0x62, 0x69, 0x6c, 0x65, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_tuning_proto_rawDescOnce sync.Once
	file_config_tuning_proto_rawDescData = file_config_tuning_proto_rawDesc
)

func file_config_tuning_proto_rawDescGZIP() []byte {
	file_config_tuning_proto_rawDescOnce.Do(func() {
		file_config_tuning_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_tuning_proto_rawDescData)
	})
	return file_config_tuning_proto_rawDescData
}

var file_config_tuning_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_tuning_proto_goTypes = []interface{}{
	(Tuning)(0), // 0: config.Tuning
}
var file_config_tuning_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_config_tuning_proto_init() }
func file_config_tuning_proto_init() {
	if File_config_tuning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_tuning_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_tuning_proto_goTypes,
		DependencyIndexes: file_config_tuning_proto_depIdxs,
		EnumInfos:         file_config_tuning_proto_enumTypes,
	}.Build()
	File_config_tuning_proto = out.File
	file_config_tuning_proto_rawDesc = nil
	file_config_tuning_proto_goTypes = nil
	file_config_tuning_proto_depIdxs = nil
}
