// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: lib/config/versioningconfiguration.proto

package config

import (
	fs "github.com/zebfross/syncthing-mobile/syncthing/fs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VersioningConfiguration is used in the code and for JSON serialization
type VersioningConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type             string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Parameters       map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CleanupIntervalS int32             `protobuf:"varint,3,opt,name=cleanup_interval_s,json=cleanupIntervalS,proto3" json:"cleanup_interval_s,omitempty"`
	FsPath           string            `protobuf:"bytes,4,opt,name=fs_path,json=fsPath,proto3" json:"fs_path,omitempty"`
	FsType           fs.FilesystemType `protobuf:"varint,5,opt,name=fs_type,json=fsType,proto3,enum=fs.FilesystemType" json:"fs_type,omitempty"`
}

func (x *VersioningConfiguration) Reset() {
	*x = VersioningConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_config_versioningconfiguration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersioningConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersioningConfiguration) ProtoMessage() {}

func (x *VersioningConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_lib_config_versioningconfiguration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersioningConfiguration.ProtoReflect.Descriptor instead.
func (*VersioningConfiguration) Descriptor() ([]byte, []int) {
	return file_lib_config_versioningconfiguration_proto_rawDescGZIP(), []int{0}
}

func (x *VersioningConfiguration) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VersioningConfiguration) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *VersioningConfiguration) GetCleanupIntervalS() int32 {
	if x != nil {
		return x.CleanupIntervalS
	}
	return 0
}

func (x *VersioningConfiguration) GetFsPath() string {
	if x != nil {
		return x.FsPath
	}
	return ""
}

func (x *VersioningConfiguration) GetFsType() fs.FilesystemType {
	if x != nil {
		return x.FsType
	}
	return fs.FilesystemType(0)
}

var File_lib_config_versioningconfiguration_proto protoreflect.FileDescriptor

var file_lib_config_versioningconfiguration_proto_rawDesc = []byte{
	0x0a, 0x28, 0x6c, 0x69, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x1a, 0x12, 0x6c, 0x69, 0x62, 0x2f, 0x66, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x02, 0x0a, 0x17, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x4f, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x6c, 0x65, 0x61, 0x6e,
	0x75, 0x70, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x10, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x75, 0x70, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x53, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x73, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x73, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2b,
	0x0a, 0x07, 0x66, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x66, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x06, 0x66, 0x73, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x3d, 0x0a, 0x0f, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x12, 0x5a, 0x10, 0x73, 0x79,
	0x6e, 0x63, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lib_config_versioningconfiguration_proto_rawDescOnce sync.Once
	file_lib_config_versioningconfiguration_proto_rawDescData = file_lib_config_versioningconfiguration_proto_rawDesc
)

func file_lib_config_versioningconfiguration_proto_rawDescGZIP() []byte {
	file_lib_config_versioningconfiguration_proto_rawDescOnce.Do(func() {
		file_lib_config_versioningconfiguration_proto_rawDescData = protoimpl.X.CompressGZIP(file_lib_config_versioningconfiguration_proto_rawDescData)
	})
	return file_lib_config_versioningconfiguration_proto_rawDescData
}

var file_lib_config_versioningconfiguration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lib_config_versioningconfiguration_proto_goTypes = []interface{}{
	(*VersioningConfiguration)(nil), // 0: config.VersioningConfiguration
	nil,                             // 1: config.VersioningConfiguration.ParametersEntry
	(fs.FilesystemType)(0),          // 2: fs.FilesystemType
}
var file_lib_config_versioningconfiguration_proto_depIdxs = []int32{
	1, // 0: config.VersioningConfiguration.parameters:type_name -> config.VersioningConfiguration.ParametersEntry
	2, // 1: config.VersioningConfiguration.fs_type:type_name -> fs.FilesystemType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lib_config_versioningconfiguration_proto_init() }
func file_lib_config_versioningconfiguration_proto_init() {
	if File_lib_config_versioningconfiguration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lib_config_versioningconfiguration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersioningConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lib_config_versioningconfiguration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lib_config_versioningconfiguration_proto_goTypes,
		DependencyIndexes: file_lib_config_versioningconfiguration_proto_depIdxs,
		MessageInfos:      file_lib_config_versioningconfiguration_proto_msgTypes,
	}.Build()
	File_lib_config_versioningconfiguration_proto = out.File
	file_lib_config_versioningconfiguration_proto_rawDesc = nil
	file_lib_config_versioningconfiguration_proto_goTypes = nil
	file_lib_config_versioningconfiguration_proto_depIdxs = nil
}
