WINDOWS_OUTPUT?=windows
WINDOWS_BINDING_NAME?=$(BINDING_NAME).dll

binding_windows: binding_windows_386 binding_windows_amd64

binding_windows_386:
	GOOS=windows GOARCH=386 CGO_ENABLED=1 \
	BINDING_FILE=$(WINDOWS_OUTPUT)/386/$(WINDOWS_BINDING_NAME) \
	TAG=main make binding

binding_windows_amd64:
	GOOS=windows GOARCH=amd64 TAG=main CGO_ENABLED=1 \
	BINDING_FILE=$(WINDOWS_OUTPUT)/amd64/$(WINDOWS_BINDING_NAME) \
	make binding
