// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: lib/fs/copyrangemethod.proto

package fs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CopyRangeMethod int32

const (
	CopyRangeMethod_COPY_RANGE_METHOD_STANDARD          CopyRangeMethod = 0
	CopyRangeMethod_COPY_RANGE_METHOD_IOCTL             CopyRangeMethod = 1
	CopyRangeMethod_COPY_RANGE_METHOD_COPY_FILE_RANGE   CopyRangeMethod = 2
	CopyRangeMethod_COPY_RANGE_METHOD_SEND_FILE         CopyRangeMethod = 3
	CopyRangeMethod_COPY_RANGE_METHOD_DUPLICATE_EXTENTS CopyRangeMethod = 4
	CopyRangeMethod_COPY_RANGE_METHOD_ALL_WITH_FALLBACK CopyRangeMethod = 5
)

// Enum value maps for CopyRangeMethod.
var (
	CopyRangeMethod_name = map[int32]string{
		0: "COPY_RANGE_METHOD_STANDARD",
		1: "COPY_RANGE_METHOD_IOCTL",
		2: "COPY_RANGE_METHOD_COPY_FILE_RANGE",
		3: "COPY_RANGE_METHOD_SEND_FILE",
		4: "COPY_RANGE_METHOD_DUPLICATE_EXTENTS",
		5: "COPY_RANGE_METHOD_ALL_WITH_FALLBACK",
	}
	CopyRangeMethod_value = map[string]int32{
		"COPY_RANGE_METHOD_STANDARD":          0,
		"COPY_RANGE_METHOD_IOCTL":             1,
		"COPY_RANGE_METHOD_COPY_FILE_RANGE":   2,
		"COPY_RANGE_METHOD_SEND_FILE":         3,
		"COPY_RANGE_METHOD_DUPLICATE_EXTENTS": 4,
		"COPY_RANGE_METHOD_ALL_WITH_FALLBACK": 5,
	}
)

func (x CopyRangeMethod) Enum() *CopyRangeMethod {
	p := new(CopyRangeMethod)
	*p = x
	return p
}

func (x CopyRangeMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CopyRangeMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_lib_fs_copyrangemethod_proto_enumTypes[0].Descriptor()
}

func (CopyRangeMethod) Type() protoreflect.EnumType {
	return &file_lib_fs_copyrangemethod_proto_enumTypes[0]
}

func (x CopyRangeMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CopyRangeMethod.Descriptor instead.
func (CopyRangeMethod) EnumDescriptor() ([]byte, []int) {
	return file_lib_fs_copyrangemethod_proto_rawDescGZIP(), []int{0}
}

var File_lib_fs_copyrangemethod_proto protoreflect.FileDescriptor

var file_lib_fs_copyrangemethod_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6c, 0x69, 0x62, 0x2f, 0x66, 0x73, 0x2f, 0x63, 0x6f, 0x70, 0x79, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x66, 0x73, 0x2a, 0xe8, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4f, 0x50, 0x59, 0x5f, 0x52,
	0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x4e,
	0x44, 0x41, 0x52, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4f, 0x50, 0x59, 0x5f, 0x52,
	0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x49, 0x4f, 0x43, 0x54,
	0x4c, 0x10, 0x01, 0x12, 0x25, 0x0a, 0x21, 0x43, 0x4f, 0x50, 0x59, 0x5f, 0x52, 0x41, 0x4e, 0x47,
	0x45, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x43, 0x4f, 0x50, 0x59, 0x5f, 0x46, 0x49,
	0x4c, 0x45, 0x5f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x02, 0x12, 0x1f, 0x0a, 0x1b, 0x43, 0x4f,
	0x50, 0x59, 0x5f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f,
	0x53, 0x45, 0x4e, 0x44, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x27, 0x0a, 0x23, 0x43,
	0x4f, 0x50, 0x59, 0x5f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44,
	0x5f, 0x44, 0x55, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x58, 0x54, 0x45, 0x4e,
	0x54, 0x53, 0x10, 0x04, 0x12, 0x27, 0x0a, 0x23, 0x43, 0x4f, 0x50, 0x59, 0x5f, 0x52, 0x41, 0x4e,
	0x47, 0x45, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x57, 0x49,
	0x54, 0x48, 0x5f, 0x46, 0x41, 0x4c, 0x4c, 0x42, 0x41, 0x43, 0x4b, 0x10, 0x05, 0x42, 0x0e, 0x5a,
	0x0c, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x66, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lib_fs_copyrangemethod_proto_rawDescOnce sync.Once
	file_lib_fs_copyrangemethod_proto_rawDescData = file_lib_fs_copyrangemethod_proto_rawDesc
)

func file_lib_fs_copyrangemethod_proto_rawDescGZIP() []byte {
	file_lib_fs_copyrangemethod_proto_rawDescOnce.Do(func() {
		file_lib_fs_copyrangemethod_proto_rawDescData = protoimpl.X.CompressGZIP(file_lib_fs_copyrangemethod_proto_rawDescData)
	})
	return file_lib_fs_copyrangemethod_proto_rawDescData
}

var file_lib_fs_copyrangemethod_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lib_fs_copyrangemethod_proto_goTypes = []interface{}{
	(CopyRangeMethod)(0), // 0: fs.CopyRangeMethod
}
var file_lib_fs_copyrangemethod_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lib_fs_copyrangemethod_proto_init() }
func file_lib_fs_copyrangemethod_proto_init() {
	if File_lib_fs_copyrangemethod_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lib_fs_copyrangemethod_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lib_fs_copyrangemethod_proto_goTypes,
		DependencyIndexes: file_lib_fs_copyrangemethod_proto_depIdxs,
		EnumInfos:         file_lib_fs_copyrangemethod_proto_enumTypes,
	}.Build()
	File_lib_fs_copyrangemethod_proto = out.File
	file_lib_fs_copyrangemethod_proto_rawDesc = nil
	file_lib_fs_copyrangemethod_proto_goTypes = nil
	file_lib_fs_copyrangemethod_proto_depIdxs = nil
}
