// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: fs/types.proto

package fs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilesystemType int32

const (
	FilesystemType_FILESYSTEM_TYPE_BASIC FilesystemType = 0
	FilesystemType_FILESYSTEM_TYPE_FAKE  FilesystemType = 1
)

// Enum value maps for FilesystemType.
var (
	FilesystemType_name = map[int32]string{
		0: "FILESYSTEM_TYPE_BASIC",
		1: "FILESYSTEM_TYPE_FAKE",
	}
	FilesystemType_value = map[string]int32{
		"FILESYSTEM_TYPE_BASIC": 0,
		"FILESYSTEM_TYPE_FAKE":  1,
	}
)

func (x FilesystemType) Enum() *FilesystemType {
	p := new(FilesystemType)
	*p = x
	return p
}

func (x FilesystemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilesystemType) Descriptor() protoreflect.EnumDescriptor {
	return file_fs_types_proto_enumTypes[0].Descriptor()
}

func (FilesystemType) Type() protoreflect.EnumType {
	return &file_fs_types_proto_enumTypes[0]
}

func (x FilesystemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilesystemType.Descriptor instead.
func (FilesystemType) EnumDescriptor() ([]byte, []int) {
	return file_fs_types_proto_rawDescGZIP(), []int{0}
}

var File_fs_types_proto protoreflect.FileDescriptor

var file_fs_types_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x66, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x66, 0x73, 0x2a, 0x45, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x46, 0x49, 0x4c, 0x45, 0x53, 0x59,
	0x53, 0x54, 0x45, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x41, 0x53, 0x49, 0x43, 0x10,
	0x00, 0x12, 0x18, 0x0a, 0x14, 0x46, 0x49, 0x4c, 0x45, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x41, 0x4b, 0x45, 0x10, 0x01, 0x42, 0x33, 0x5a, 0x31, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x65, 0x62, 0x66, 0x72, 0x6f,
	0x73, 0x73, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2d, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x66, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fs_types_proto_rawDescOnce sync.Once
	file_fs_types_proto_rawDescData = file_fs_types_proto_rawDesc
)

func file_fs_types_proto_rawDescGZIP() []byte {
	file_fs_types_proto_rawDescOnce.Do(func() {
		file_fs_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_fs_types_proto_rawDescData)
	})
	return file_fs_types_proto_rawDescData
}

var file_fs_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fs_types_proto_goTypes = []interface{}{
	(FilesystemType)(0), // 0: fs.FilesystemType
}
var file_fs_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fs_types_proto_init() }
func file_fs_types_proto_init() {
	if File_fs_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fs_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fs_types_proto_goTypes,
		DependencyIndexes: file_fs_types_proto_depIdxs,
		EnumInfos:         file_fs_types_proto_enumTypes,
	}.Build()
	File_fs_types_proto = out.File
	file_fs_types_proto_rawDesc = nil
	file_fs_types_proto_goTypes = nil
	file_fs_types_proto_depIdxs = nil
}
