// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LinkDeviceIdRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsLinkDeviceIdRequest(buf []byte, offset flatbuffers.UOffsetT) *LinkDeviceIdRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LinkDeviceIdRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsLinkDeviceIdRequest(buf []byte, offset flatbuffers.UOffsetT) *LinkDeviceIdRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LinkDeviceIdRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *LinkDeviceIdRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LinkDeviceIdRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LinkDeviceIdRequest) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LinkDeviceIdRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LinkDeviceIdRequestAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(deviceId), 0)
}
func LinkDeviceIdRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
